#!/usr/bin/env perl

use strict;
use warnings;

sub make_trie {
  my %t;
  my $depth = shift;
  my $switch = "scanner->start[${\ ($depth - 1) }]";
  local $_;
  for (@_) {
    push(@{ $t{substr($_, $depth - 1, 1)} ||= [] }, $_);
  }

  my @lines = (
    "if ((scanner->current - scanner->start) > ${\($depth - 1)}) {",
    "  switch($switch) {"
  );

  foreach my $k (sort keys(%t)) {
    my @v = @{ $t{$k} };

    push @lines, sprintf "    case '%s':",
      substr($v[0], $depth - 1, 1);

    if (scalar(@v) > 1 ){
      push @lines, make_trie($depth + 1, @v);
    } else {
      my $s = $v[0];
      push @lines,
        sprintf "      return check_keyword(scanner, %d, %d, \"%s\", TOKEN_%s);",
          $depth, length($s) - $depth, substr($s, $depth), uc($s);
    }
  }

  push @lines, "  }", "}";
  push @lines, "break;" if $depth > 1;

  join("\n", @lines) =~ s/^/${\ ("  " x ($depth + 1)) }/mgr;
};

my @tokens;
my $in_keywords;
my @keywords;

open(FH, "<", $ARGV[0]) or die $!;
while (<FH>) {
  push @tokens, $_;

  if (/# (\w+)/){
    $in_keywords = $1 eq "Keywords";
  }
  elsif($in_keywords && /^\S/){
    chomp;
    push @keywords, lc $_;
  }
}
close(FH);

my $s = join "", <DATA>;
my %vars = (
  gen => "// generated by @{ [$0 =~ m{([^/]+/[^/]+)$}] }",
  trie => make_trie(1, @keywords),
);
print($s =~ s/^#= (\w+)$/$vars{$1}/gmr);

__DATA__
#= gen

#ifndef CLOX_GEN_IDENT_H
#define CLOX_GEN_IDENT_H

#include <string.h>

static token_type_t check_keyword(scanner_t *scanner, int start, int length, const char *rest, token_type_t type) {
  if (scanner->current - scanner->start == start + length &&
      memcmp(scanner->start + start, rest, length) == 0) {
    return type;
  }

  return TOKEN_IDENTIFIER;
}

token_type_t identifier_type(scanner_t *scanner) {

#= trie

  return TOKEN_IDENTIFIER;
}

#endif
